#ifndef DEFAULTS_CALIBRATION_H
#define DEFAULTS_CALIBRATION_H


#define CALIB_DEFAULT_TEMPERATURE_CALIB_METHOD      0
#define CALIB_DEFAULT_TEMPERATURE_T_CONTROL_ENABLE  false
#define CALIB_DEFAULT_TEMPERATURE_T                 20.0

#define CALIB_DEFAULT_TEMPERATURE_T_LOW             20.0
#define CALIB_DEFAULT_TEMPERATURE_T_LOW_COUNT       46810

#define CALIB_DEFAULT_TEMPERATURE_T_HIGH            38.00
#define CALIB_DEFAULT_TEMPERATURE_T_HIGH_COUNT      72970

#define CALIB_DEFAULT_TEMPERATURE_ZERO              0.0
#define CALIB_DEFAULT_TEMPERATURE_OFFSET            0.1
#define CALIB_DEFAULT_TEMPERATURE_GAIN              1.0


#define CALIB_DEFAULT_PRESSURE_T_CONTROL_ENABLE  true
#define CALIB_DEFAULT_PRESSURE_T                 20.0

#define CALIB_DEFAULT_PRESSURE_P_LOW             0
#define CALIB_DEFAULT_PRESSURE_P_LOW_COUNT       17510

#define CALIB_DEFAULT_PRESSURE_P_HIGH            101.3
#define CALIB_DEFAULT_PRESSURE_P_HIGH_COUNT      26265

#define CALIB_DEFAULT_PRESSURE_ZERO              0.0
#define CALIB_DEFAULT_PRESSURE_OFFSET            1.1
#define CALIB_DEFAULT_PRESSURE_GAIN              1.99

#define CALIB_DEFAULT_PRESSURE_SELECTOR_VALVE_POSITION   0

#define CALIB_DEFAULT_PRESSURE_T_FIRST             0.0
#define CALIB_DEFAULT_PRESSURE_T_FINAL             100.0

#define CALIB_DEFAULT_PRESSURE_ZERO_CORRECTION_MIN  -10.00
#define CALIB_DEFAULT_PRESSURE_ZERO_CORRECTION_MAX  10.00

#define CALIB_DEFAULT_PRESSURE_AMBIENT_CORRECTION_MIN  -10.00
#define CALIB_DEFAULT_PRESSURE_AMBIENT_CORRECTION_MAX  10.00


#define RANGE_CALIB_TEMPERATURE_MIN               0.00
#define RANGE_CALIB_TEMPERATURE_MAX               100.00
#define RANGE_CALIB_TEMPERATURE_DECIMAL_PLACES    2

#define RANGE_CALIB_TEMPERATURE_OFFSET_MIN        -5.00
#define RANGE_CALIB_TEMPERATURE_OFFSET_MAX        5.00

#define RANGE_CALIB_PRESSURE_MIN                  -5        
#define RANGE_CALIB_PRESSURE_MAX                  101.3 + 5
#define RANGE_CALIB_PRESSURE_DECIMAL_PLACES       1

#define RANGE_CALIB_PRESSURE_CORRECTION_MIN                  -99 
#define RANGE_CALIB_PRESSURE_CORRECTION_MAX                  +99 
#define RANGE_CALIB_PRESSURE_CORRECTION_DECIMAL_PLACES       2

#define AVG_BUFFER_SIZE 5
#define AVG_WAIT_PERIOD 10       

#define AVG_TYPE_NONE           0
#define AVG_TYPE_TEMPERATURE    1
#define AVG_TYPE_PRESSURE       2


#endif // DEFAULTS_CALIBRATION_H
